version: '3.8'

services:
  nginx:
    container_name: nginx
    image: dahuikim/nursetest-nginx:${TAG}
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - jenkins-network
    volumes:
      - /policy:/usr/share/nginx/html
    depends_on:
      - app

  app:
    container_name: app
    image: dahuikim/nursetest-app:${TAG}
    build:
      context: backend
      dockerfile: redis/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"


  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    build:
      context: redis
      dockerfile: redis/Dockerfile
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - ~/redis/data:/data
    user: root
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

networks:
  jenkins-network:
    external: true
